### ISSUE TITLE
Deploy frax.convexfinance USDC strategy

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#167]
Convex Finance now supports Frax gauges. Best USDC yield is frax.convexfinance FraxBP (7.5% APY) Regular FraxBP Convex pool is only 3.5% APY

Frax.convex strategy has additional complexity - you have to initialize your own vault and initiate a one-time lockup of at least 1 day on the UI (unsure if can do lower deposit from contract directly).

**Comment by patidarmanoj10** [comment]
@green-jeff we did some analysis. It seems that this implementation isn't too simple, as you said, it isn't only matter of changing the gauge contract. The Convex-Frax contracts have different interface than Convex-Curve. For instance, 1) to deposit crvFRAX (FRAX/USDC Curve LP token) users have to deploy a vault contract first then interact with it and 2) In order to stake to Frax, we have to lock the tokens for some time (_secs param).
 
 This is new strategy altogether. We are adding this in development queue now.
