### ISSUE TITLE
Optimism Pool Deployments

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#239]
Deploy ETH, USDC, and OP pools to Optimism.

Strategy deployment prioritization on these pools is as follows:

1. Alpha Homora #235 
2. Curve #236 
3. Stargate #237 
4. Aave v3 #238 

Note that Alpha Homora may have a quirk that translates to auditing required. If that is the case, prioritize Curve first.

**Comment by patidarmanoj10** [comment]
@virendrapatidar Let get ready with Alpha Homora.  Check unit test is passing with OP and alpha homora . cc @rokso

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
I am preparing config for vaETH pool with Alpha Homora first.

**Comment by virendrapatidar** [comment]
Do not find Alpha token rewards on optimism chain
https://docs.alphaventuredao.io/homora-v2/additional-information/usdalpha-token-address

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

- We kept Alpha Homora on hold due to source code is not being verified
- Curve strategy is deployed for vaETH and vaUSDC pool. These two pools are seed tested and all looking okay.
- Stargate strategy is blocked. More details [here](https://github.com/vesperfi/vesper-pool-ops/issues/237#issuecomment-1443669723)
- Aave v3 - configuration is okay for the vaETH pool, PR raised. For vaOP pool, we do not have AToken. More details [here](https://github.com/vesperfi/vesper-pool-ops/issues/238#issuecomment-1446470153)

**Comment by patidarmanoj10** [comment]
Good to close this after Aave V3 is done.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
As of now, only vaETH and vaUSDC pools are deployed. Do we need a vaOP pool as well?

**Comment by virendrapatidar** [comment]
Do not see a valid strategy that can be deployed for the vaOP pool. 
Closing this ticket for now.
